apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
      - name: classificacao
        image: tti301_mss_classificacao
        resources:
          limits:
            memory: 256Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: classificacao-service
spec:
  type: ClusterIP
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000