apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - name: logs
        image: tti301_mss_logs
        resources:
          limits:
            memory: 256Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: logs-service
spec:
  type: ClusterIP
  selector:
    app: logs
  ports:
    - name: logs
      protocol: TCP
      port: 8000
      targetPort: 8000