apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
      - name: observacoes
        image: tti301_mss_lembretes
        resources:
          limits:
            memory: 256Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  type: ClusterIP
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000